"""
Management command: fetch_github_snippets
-----------------------------------------
Fetches real code snippets from popular public GitHub repositories
via the GitHub API and saves them to the Snippet model.

Usage:
    python manage.py fetch_github_snippets --token <GITHUB_TOKEN> [--per-lang 30] [--clear]

Options:
    --token     GitHub Personal Access Token (or set GITHUB_TOKEN in .env)
    --per-lang  Number of snippets to fetch per language (default: 30)
    --clear     Delete all existing GitHub-sourced snippets before fetching
    --dry-run   Print snippets without saving to DB
    --lang      Fetch only for this language slug (e.g. python)
"""

import random
import re
import time

import requests
from django.core.management.base import BaseCommand, CommandError

from trainer.models import Language, Snippet

# ---------------------------------------------------------------------------
# Configuration: which repos to search per language slug
# ---------------------------------------------------------------------------
REPO_QUERIES = {
    "python": [
        "pallets/flask",
        "psf/requests",
        "django/django",
        "scikit-learn/scikit-learn",
        "tiangolo/fastapi",
        "encode/httpx",
        "boto/boto3",
        "sqlalchemy/sqlalchemy",
    ],
    "javascript": [
        "expressjs/express",
        "lodash/lodash",
        "axios/axios",
        "moment/moment",
        "sindresorhus/got",
        "vercel/next.js",
        "jquense/yup",
        "winstonjs/winston",
    ],
    "java": [
        "spring-projects/spring-framework",
        "square/okhttp",
        "google/guava",
        "ReactiveX/RxJava",
        "junit-team/junit5",
        "apache/commons-lang",
    ],
    "cpp": [
        "nlohmann/json",
        "google/googletest",
        "catchorg/Catch2",
        "fmtlib/fmt",
        "bblanchon/ArduinoJson",
        "abseil/abseil-cpp",
    ],
    "go": [
        "gin-gonic/gin",
        "go-chi/chi",
        "labstack/echo",
        "gorilla/mux",
        "spf13/cobra",
        "uber-go/zap",
    ],
    "sql": [
        "datafold/data-diff",
        "sqlfluff/sqlfluff",
        "dbt-labs/dbt-core",
    ],
    "css": [
        "necolas/normalize.css",
        "animate-css/animate.css",
        "twbs/bootstrap",
        "Dogfalo/materialize",
        "foundation/foundation-sites",
        "jgthms/bulma",
    ],
}

# File extensions to look for per language slug
EXTENSIONS = {
    "python": [".py"],
    "javascript": [".js", ".ts"],
    "java": [".java"],
    "cpp": [".cpp", ".cc", ".cxx"],
    "go": [".go"],
    "sql": [".sql"],
    "css": [".css"],
}

# Difficulty thresholds (lines)
EASY_MAX = 10
MEDIUM_MAX = 20

# Minimum/maximum snippet length
MIN_LINES = 4
MAX_LINES = 25

# Patterns indicating we should skip a file/chunk
SKIP_PATTERNS = [
    re.compile(r"^\s*(#|//)\s*(Copyright|License|AUTO-GENERATED|Generated by|DO NOT EDIT)", re.IGNORECASE),
    re.compile(r".{200,}"),  # very long lines (minified)
]

# Source tag embedded in title to identify GitHub-imported snippets
SOURCE_TAG = "[GH]"


def _classify_difficulty(lines: list) -> str:
    n = len(lines)
    if n <= EASY_MAX:
        return "easy"
    if n <= MEDIUM_MAX:
        return "medium"
    return "hard"


def _should_skip(code: str) -> bool:
    for pat in SKIP_PATTERNS:
        if pat.search(code):
            return True
    lines = code.splitlines()
    blank = sum(1 for l in lines if l.strip() == "")
    if lines and blank / len(lines) > 0.5:
        return True
    return False


def _sliding_window(lines: list, step: int = 8) -> list:
    chunks = []
    i = 0
    while i < len(lines):
        window = lines[i: i + MAX_LINES]
        if len(window) >= MIN_LINES:
            chunks.append("\n".join(window))
        i += step
    return chunks


def _extract_python_chunks(lines: list) -> list:
    chunks = []
    func_starts = []
    for idx, line in enumerate(lines):
        if re.match(r"^(def |class )\w", line):
            func_starts.append(idx)
    for i, start in enumerate(func_starts):
        end = func_starts[i + 1] if i + 1 < len(func_starts) else len(lines)
        block = lines[start:min(end, start + MAX_LINES)]
        while block and block[-1].strip() == "":
            block.pop()
        if block:
            chunks.append("\n".join(block))
    return chunks or _sliding_window(lines)


def _extract_js_chunks(lines: list) -> list:
    chunks = []
    func_starts = []
    pattern = re.compile(
        r"^(export\s+)?(async\s+)?function\s+\w|^\s*(const|let|var)\s+\w+\s*=\s*(async\s+)?\("
    )
    for idx, line in enumerate(lines):
        if pattern.match(line):
            func_starts.append(idx)
    for i, start in enumerate(func_starts):
        end = func_starts[i + 1] if i + 1 < len(func_starts) else len(lines)
        block = lines[start:min(end, start + MAX_LINES)]
        while block and block[-1].strip() == "":
            block.pop()
        if block:
            chunks.append("\n".join(block))
    return chunks or _sliding_window(lines)


def _extract_java_chunks(lines: list) -> list:
    chunks = []
    method_starts = []
    pattern = re.compile(r"^\s+(public|private|protected|static|final|void|\w+)\s+\w+\s*\(")
    for idx, line in enumerate(lines):
        if pattern.match(line):
            method_starts.append(idx)
    for i, start in enumerate(method_starts):
        end = method_starts[i + 1] if i + 1 < len(method_starts) else len(lines)
        block = lines[start:min(end, start + MAX_LINES)]
        while block and block[-1].strip() == "":
            block.pop()
        if block:
            chunks.append("\n".join(block))
    return chunks or _sliding_window(lines)


def _extract_go_chunks(lines: list) -> list:
    chunks = []
    func_starts = []
    for idx, line in enumerate(lines):
        if re.match(r"^func\s+", line):
            func_starts.append(idx)
    for i, start in enumerate(func_starts):
        end = func_starts[i + 1] if i + 1 < len(func_starts) else len(lines)
        block = lines[start:min(end, start + MAX_LINES)]
        while block and block[-1].strip() == "":
            block.pop()
        if block:
            chunks.append("\n".join(block))
    return chunks or _sliding_window(lines)


def _extract_chunks(content: str, language_slug: str) -> list:
    lines = content.splitlines()
    if language_slug == "python":
        chunks = _extract_python_chunks(lines)
    elif language_slug == "javascript":
        chunks = _extract_js_chunks(lines)
    elif language_slug == "java":
        chunks = _extract_java_chunks(lines)
    elif language_slug == "go":
        chunks = _extract_go_chunks(lines)
    else:
        chunks = _sliding_window(lines)

    result = []
    for chunk in chunks:
        chunk_lines = chunk.splitlines()
        if MIN_LINES <= len(chunk_lines) <= MAX_LINES and not _should_skip(chunk):
            result.append(chunk)
    return result


class GitHubClient:
    BASE = "https://api.github.com"

    def __init__(self, token: str):
        self.session = requests.Session()
        self.session.headers.update({
            "Authorization": f"Bearer {token}",
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        })

    def _get(self, url: str, params: dict = None, retries: int = 3):
        for attempt in range(retries):
            try:
                r = self.session.get(url, params=params, timeout=15)
                if r.status_code == 403:
                    reset = int(r.headers.get("X-RateLimit-Reset", time.time() + 60))
                    wait = max(reset - int(time.time()), 1)
                    print(f"  [rate limit] sleeping {wait}s ...")
                    time.sleep(wait)
                    continue
                if r.status_code == 404:
                    return None
                r.raise_for_status()
                return r.json()
            except requests.RequestException as e:
                if attempt == retries - 1:
                    print(f"  [error] {e}")
                    return None
                time.sleep(2 ** attempt)
        return None

    def list_repo_files(self, repo: str, ext: str, branch: str = "HEAD") -> list:
        url = f"{self.BASE}/repos/{repo}/git/trees/{branch}"
        data = self._get(url, params={"recursive": "1"})
        if not data or "tree" not in data:
            return []
        return [
            item["path"]
            for item in data["tree"]
            if item["type"] == "blob"
            and item["path"].endswith(ext)
            and "test" not in item["path"].lower()
            and "vendor" not in item["path"].lower()
            and "node_modules" not in item["path"].lower()
            and "migration" not in item["path"].lower()
        ]

    def get_file_content(self, repo: str, path: str):
        url = f"https://raw.githubusercontent.com/{repo}/HEAD/{path}"
        try:
            r = self.session.get(url, timeout=15)
            r.raise_for_status()
            return r.text
        except requests.RequestException:
            return None

    def get_default_branch(self, repo: str) -> str:
        data = self._get(f"{self.BASE}/repos/{repo}")
        if data:
            return data.get("default_branch", "main")
        return "main"


class Command(BaseCommand):
    help = "Fetch real code snippets from public GitHub repos and save to DB."

    def add_arguments(self, parser):
        parser.add_argument("--token", type=str, default="",
                            help="GitHub Personal Access Token (or set GITHUB_TOKEN in .env).")
        parser.add_argument("--per-lang", type=int, default=30,
                            help="Target number of snippets per language (default: 30).")
        parser.add_argument("--clear", action="store_true",
                            help="Delete existing GitHub-sourced snippets before fetching.")
        parser.add_argument("--dry-run", action="store_true",
                            help="Print snippets without saving to DB.")
        parser.add_argument("--lang", type=str, default="",
                            help="Fetch only for this language slug (e.g. python).")

    def handle(self, *args, **options):
        import os

        token = options["token"] or os.environ.get("GITHUB_TOKEN", "")
        if not token:
            try:
                from decouple import config
                token = config("GITHUB_TOKEN", default="")
            except Exception:
                pass

        if not token:
            raise CommandError(
                "GitHub token not found.\n"
                "Pass --token <TOKEN>  or add GITHUB_TOKEN=<TOKEN> to your .env file."
            )

        per_lang = options["per_lang"]
        dry_run = options["dry_run"]
        only_lang = options["lang"].strip().lower()

        client = GitHubClient(token)

        if options["clear"] and not dry_run:
            deleted, _ = Snippet.objects.filter(title__startswith=SOURCE_TAG).delete()
            self.stdout.write(self.style.WARNING(f"Deleted {deleted} existing GitHub snippets."))

        lang_slugs = [only_lang] if only_lang else list(REPO_QUERIES.keys())

        for lang_slug in lang_slugs:
            lang_obj = Language.objects.filter(slug=lang_slug).first()
            if not lang_obj:
                self.stdout.write(self.style.WARNING(
                    f"Language '{lang_slug}' not found in DB — skipping."
                ))
                continue

            repos = REPO_QUERIES.get(lang_slug, [])
            exts = EXTENSIONS.get(lang_slug, [".py"])

            self.stdout.write(f"\n{'=' * 60}")
            self.stdout.write(f"Language: {lang_slug.upper()}  (target: {per_lang} snippets)")
            self.stdout.write(f"{'=' * 60}")

            collected = []
            repos_shuffled = repos[:]
            random.shuffle(repos_shuffled)

            for repo in repos_shuffled:
                if len(collected) >= per_lang:
                    break

                self.stdout.write(f"  Repo: {repo}")
                branch = client.get_default_branch(repo)

                for ext in exts:
                    if len(collected) >= per_lang:
                        break

                    paths = client.list_repo_files(repo, ext, branch)
                    if not paths:
                        continue

                    random.shuffle(paths)
                    for path in paths[:10]:
                        if len(collected) >= per_lang:
                            break

                        content = client.get_file_content(repo, path)
                        if not content or len(content) > 50_000:
                            continue

                        chunks = _extract_chunks(content, lang_slug)
                        random.shuffle(chunks)

                        repo_name = repo.split("/")[-1]
                        file_name = path.split("/")[-1]

                        for chunk in chunks[:3]:
                            if len(collected) >= per_lang:
                                break
                            difficulty = _classify_difficulty(chunk.splitlines())
                            title = f"{SOURCE_TAG} {repo_name} — {file_name}"
                            collected.append({
                                "code": chunk,
                                "title": title,
                                "difficulty": difficulty,
                            })
                            self.stdout.write(
                                f"    + [{difficulty:6}] {title[:60]}"
                            )

                time.sleep(0.3)

            self.stdout.write(
                f"\n  Collected {len(collected)} snippets for {lang_slug}."
            )

            if not dry_run:
                created = 0
                for item in collected:
                    _, was_created = Snippet.objects.get_or_create(
                        language=lang_obj,
                        title=item["title"],
                        code=item["code"],
                        defaults={"difficulty": item["difficulty"]},
                    )
                    if was_created:
                        created += 1
                self.stdout.write(
                    self.style.SUCCESS(f"  Saved {created} new snippets for {lang_slug}.")
                )
            else:
                self.stdout.write(self.style.WARNING("  [dry-run] Nothing saved."))

        self.stdout.write(self.style.SUCCESS("\nDone!"))
