# Generated by Django 5.1.1 on 2026-09-24 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript / TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('sql', 'SQL')], max_length=20, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('icon', models.CharField(default='💻', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Snippet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10)),
                ('title', models.CharField(max_length=100)),
                ('code', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snippets', to='trainer.language')),
            ],
        ),
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wpm', models.FloatField()),
                ('cpm', models.FloatField()),
                ('accuracy', models.FloatField()),
                ('time_seconds', models.FloatField()),
                ('errors_json', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to=settings.AUTH_USER_MODEL)),
                ('snippet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='trainer.snippet')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
