# Generated by Django 5.1.1 on 2026-09-26 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0002_snippet_imported_by_alter_snippet_title_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript / TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('sql', 'SQL'), ('css', 'CSS')], max_length=20, unique=True),
        ),
    ]
