# Generated by Django 5.1.1 on 2026-09-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0003_alter_language_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='extra_exercise_seconds',
            field=models.FloatField(default=0.0, help_text='Additional exercise time from practice sessions in seconds'),
        ),
    ]
