# Generated by Django 5.1.1 on 2026-09-27 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0004_userprofile_extra_exercise_seconds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='language',
            name='slug',
            field=models.CharField(choices=[('python', 'Python'), ('javascript', 'JavaScript / TypeScript'), ('java', 'Java'), ('cpp', 'C++'), ('go', 'Go'), ('sql', 'SQL'), ('css', 'CSS'), ('bash', 'Bash')], max_length=20, unique=True),
        ),
    ]
