# Generated by Django 5.1.1 on 2026-09-28 17:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0006_alter_language_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('path', models.CharField(db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=64)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet'), ('bot', 'Bot')], db_index=True, default='desktop', max_length=20)),
                ('browser', models.CharField(blank=True, max_length=50)),
                ('referer', models.CharField(blank=True, max_length=500)),
                ('status_code', models.PositiveSmallIntegerField(default=200)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_visits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'session_key'], name='trainer_sit_timesta_7c3bed_idx'), models.Index(fields=['timestamp', 'user'], name='trainer_sit_timesta_9823c0_idx'), models.Index(fields=['timestamp', 'device_type'], name='trainer_sit_timesta_079349_idx')],
            },
        ),
    ]
