# Generated by Django 5.1.1 on 2026-09-28 17:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainer', '0007_sitevisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitevisit',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
