"""
trainer.snippet_validator
-------------------------
Comprehensive quality validator and filter for code snippets.
Ensures code is syntactically sound, complete, substantive, and
well-formatted for typing practice. Rejects garbage (unbalanced braces,
pure docstrings, license headers, Jinja templates, truncated fragments, etc.).
"""

import ast
import re
import textwrap

# ---------------------------------------------------------------------------
# Path exclusion regex
# ---------------------------------------------------------------------------
EXCLUDED_PATH_PATTERNS = [
    # Metadata & package config
    r"(^|/)(__init__|__version__|_version|setup|conftest|conf)\.py$",
    r"(^|/)(package|package-lock|tsconfig|webpack\.config|vite\.config)\.json$",
    r"(^|/)(composer|symfony)\.json$",
    # Type definitions & minified files
    r"\.d\.ts$",
    r"\.min\.(js|css)$",
    r"\.map$",
    r"(^|/)(bundle|vendor|min)\.(js|css)$",
    # Tests & mocks
    r"(^|/)(test|tests|spec|specs|mock|mocks|__tests__|__mocks__)/",
    r"(^|/)(test_.*|.*_test|.*\.test|.*\.spec)\.(py|js|ts|jsx|tsx|go|java|cpp|cc|cxx|cs|php)$",
    r"(^|/)Test[A-Z].*\.java$",
    # Documentation & localization
    r"(^|/)(doc|docs|documentation|examples?|samples?|tutorial)/",
    r"(^|/)(locale|locales|i18n|lang|translations)/",
    # Generated, migrations, vendor
    r"(^|/)(vendor|node_modules|dist|build|out|target|generated|\.github|\.git)/",
    r"(^|/)(migrations?|fixtures?)/",
    r"\.pb\.go$",
    r"\.generated\.",
]

EXCLUDED_PATH_REGEX = re.compile("|".join(EXCLUDED_PATH_PATTERNS), re.IGNORECASE)

INVALID_START_TOKENS = (
    "}", "};", "]", "];", ")", ");", "},",
    "->", "=>", "&&", "||", "+", ",", ".",
    "else:", "elif ", "else {", "elif:",
    "catch (", "catch {", "finally {", "finally:",
    "case ", "default:",
)

LICENSE_KEYWORDS = (
    "copyright", "spdx-license-identifier", "all rights reserved",
    "apache license", "mit license", "gpl license", "mozilla public license",
    "licensed under the apache", "licensed under", "auto-generated",
    "generated by", "do not edit", "this file is part of",
)


def is_excluded_file_path(path: str) -> bool:
    """Return True if path points to a test, config, locale, doc, or non-code file."""
    if not path:
        return False
    normalized = path.replace("\\", "/")
    return bool(EXCLUDED_PATH_REGEX.search(normalized))


def clean_snippet_code(code: str) -> str:
    """Strip trailing whitespace from lines and dedent common indent."""
    if not code:
        return ""
    lines = [l.rstrip() for l in code.splitlines()]
    # Remove leading and trailing empty lines
    while lines and not lines[0].strip():
        lines.pop(0)
    while lines and not lines[-1].strip():
        lines.pop()
    text = "\n".join(lines)
    return textwrap.dedent(text).strip()


def is_valid_snippet(code: str, language_slug: str) -> tuple[bool, str]:
    """
    Validate whether a snippet meets high quality standards for typing trainer.
    Returns (True, 'ok') or (False, reason_description).
    """
    cleaned = clean_snippet_code(code)
    if not cleaned:
        return False, "empty_code"

    lines = cleaned.splitlines()
    non_empty = [l.strip() for l in lines if l.strip()]

    # 1. Line count bounds
    if len(non_empty) < 4:
        return False, "too_few_lines"
    if len(lines) > 40:
        return False, "too_many_lines"

    # 2. Blank line ratio (max 35%)
    blank_count = len(lines) - len(non_empty)
    if blank_count / len(lines) > 0.35:
        return False, "too_many_blank_lines"

    # 3. Maximum line length (reject minified code or huge literals)
    if any(len(l) > 130 for l in lines):
        return False, "line_too_long"

    # 4. Invalid starting token (continuation of cut-off block)
    first_line = non_empty[0]
    invalid_tokens = INVALID_START_TOKENS
    if language_slug == "css":
        # In CSS, class selectors start with '.'
        invalid_tokens = tuple(t for t in INVALID_START_TOKENS if t != ".")

    if first_line.startswith(invalid_tokens):
        return False, f"invalid_start_token: {first_line[:20]}"
    if first_line.startswith(('"', "'")) and first_line.endswith((",", ";")) and not first_line.startswith(('"""', "'''")):
        return False, "fragment_key_value"
    if first_line.startswith(("FileField", "db.Column", "db.relationship", "db.DateTime", "db.Integer", "db.String", "models.Char", "models.Foreign")):
        return False, "cut_off_field"

    # 5. Comment / Docstring checks
    if (cleaned.startswith('"""') and cleaned.endswith('"""')) or (cleaned.startswith("'''") and cleaned.endswith("'''")):
        inner = cleaned[3:-3].strip()
        if '"""' not in inner and "'''" not in inner:
            return False, "pure_docstring"
    if (cleaned.startswith("/*") and cleaned.endswith("*/")):
        return False, "pure_comment_block"
    if (cleaned.startswith("<!--") and cleaned.endswith("-->")):
        return False, "pure_comment_block"

    # In CSS, '--' is a custom property declaration (var), not a comment!
    comment_prefixes = ["#", "//", "*", "/*", "*/", "<!--", "-->", "{-"]
    if language_slug in ("sql", "haskell", "lua"):
        comment_prefixes.append("--")
    comment_prefix_tuple = tuple(comment_prefixes)

    comment_lines = [l for l in non_empty if l.startswith(comment_prefix_tuple)]
    if len(comment_lines) / len(non_empty) >= 0.40:
        return False, "mostly_comments"

    substantive_lines = len(non_empty) - len(comment_lines)
    if substantive_lines < 3:
        return False, "insufficient_code_lines"

    # Snippets should not end with an incomplete trailing comment
    if non_empty[-1].startswith(comment_prefix_tuple) and not non_empty[-1].endswith("*/"):
        return False, "ends_with_comment"

    # 6. License header check
    first_3_text = " ".join(non_empty[:3]).lower()
    if any(kw in first_3_text for kw in LICENSE_KEYWORDS):
        return False, "license_header"

    # 7. Import / include ratio check
    import_lines = [l for l in non_empty if l.startswith(("import ", "from ", "#include ", "using ", "package ", "require("))]
    if len(import_lines) / len(non_empty) >= 0.50:
        return False, "mostly_imports"

    # 8. Brace & Bracket balance for brace-based languages
    if language_slug in ("java", "javascript", "cpp", "csharp", "php", "go", "css"):
        open_b = cleaned.count("{")
        close_b = cleaned.count("}")
        if open_b != close_b:
            return False, f"unbalanced_braces({open_b}!={close_b})"

        # Meaningful blocks in these languages must have braces
        if language_slug in ("java", "cpp", "csharp", "go", "css") and open_b < 1:
            return False, "no_braces_in_block"

    # 9. Parentheses balance
    if language_slug in ("java", "javascript", "cpp", "csharp", "go", "python", "php"):
        open_p = cleaned.count("(")
        close_p = cleaned.count(")")
        if open_p != close_p:
            return False, f"unbalanced_parens({open_p}!={close_p})"

    # 10. Square brackets balance
    if language_slug in ("java", "javascript", "cpp", "csharp", "go", "python", "php", "css"):
        open_sq = cleaned.count("[")
        close_sq = cleaned.count("]")
        if open_sq != close_sq:
            return False, f"unbalanced_brackets({open_sq}!={close_sq})"

    # 11. Orphan closing brace at end
    if non_empty[-1] in ("}", "};") and len(non_empty) >= 3:
        indent_first = len(lines[0]) - len(lines[0].lstrip())
        indent_last = len(lines[-1]) - len(lines[-1].lstrip())
        if indent_last < indent_first:
            return False, "orphan_closing_brace"

    # 12. Language-specific AST and syntactic rules
    if language_slug == "python":
        try:
            tree = ast.parse(cleaned)
        except (SyntaxError, IndentationError) as e:
            return False, f"python_syntax_error: {e}"

        has_func_or_class = any(isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)) for node in ast.walk(tree))
        if not has_func_or_class:
            # Check if it looks like loose model/form attributes extracted from class body
            if any(re.search(r"\b(db\.(Column|relationship|Date|String|Integer|DateTime)|models\.|Field\(|FormField\(|SubmitField\(|TextAreaField\()", l) for l in non_empty):
                return False, "fragmented_class_attributes"

        substantive = False
        for node in ast.walk(tree):
            if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef,
                                 ast.Assign, ast.AnnAssign, ast.For, ast.AsyncFor,
                                 ast.While, ast.If, ast.With, ast.AsyncWith,
                                 ast.Call, ast.Return, ast.Raise, ast.Try)):
                substantive = True
                break
        if not substantive:
            return False, "no_substantive_python_code"

    elif language_slug == "sql":
        if "{%" in cleaned or "{{" in cleaned or "{#" in cleaned:
            return False, "sql_jinja_template"
        sql_keywords = re.compile(
            r"\b(SELECT|INSERT\s+INTO|UPDATE\s+\w+|DELETE\s+FROM|CREATE\s+(UNIQUE\s+)?(TABLE|INDEX|VIEW)|ALTER\s+TABLE|WITH\s+\w+|DROP\s+TABLE|ANALYZE|DO\s+\$\$|DECLARE|BEGIN)\b",
            re.IGNORECASE
        )
        if not sql_keywords.search(cleaned):
            return False, "no_sql_query_keywords"

    elif language_slug == "html":
        # Must start with an open tag or <!DOCTYPE>
        if not re.match(r"^\s*<(!DOCTYPE|[a-zA-Z])", cleaned, re.IGNORECASE):
            return False, "html_does_not_start_with_tag"
        if cleaned.strip().startswith("</"):
            return False, "html_starts_with_closing_tag"
        if "{%" in cleaned or "{{" in cleaned:
            return False, "html_jinja_template"

    elif language_slug == "bash":
        if re.search(r"\bif\s+\[", cleaned) and not re.search(r"\bfi\b", cleaned):
            return False, "bash_unclosed_if"
        if re.search(r"\b(while|for)\b", cleaned) and re.search(r"\bdo\b", cleaned) and not re.search(r"\bdone\b", cleaned):
            return False, "bash_unclosed_loop"
        if re.search(r"\bcase\b", cleaned) and not re.search(r"\besac\b", cleaned):
            return False, "bash_unclosed_case"

    return True, "ok"


# ---------------------------------------------------------------------------
# AST & Structural Block Extractors
# ---------------------------------------------------------------------------

def extract_python_snippets(content: str, max_lines: int = 35) -> list[str]:
    """Extract functions, classes, and substantive top-level blocks from Python source code."""
    chunks = []
    try:
        tree = ast.parse(content)
    except Exception:
        return []

    lines = content.splitlines()
    for node in ast.walk(tree):
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            start = node.lineno - 1
            end = getattr(node, "end_lineno", None)
            if end is None:
                continue
            block_lines = lines[start:end]
            chunk = clean_snippet_code("\n".join(block_lines))
            ok, _ = is_valid_snippet(chunk, "python")
            if ok and len(chunk.splitlines()) <= max_lines:
                chunks.append(chunk)

    # Fallback for scripts without def/class (top-level statements)
    if not chunks and tree.body:
        for diff, min_l, max_l in [("easy", 5, 10), ("medium", 12, 19), ("hard", 21, 32)]:
            for i in range(0, len(lines), max_l):
                window = lines[i : i + max_l]
                if min_l <= len(window) <= max_l:
                    chunk = clean_snippet_code("\n".join(window))
                    ok, _ = is_valid_snippet(chunk, "python")
                    if ok:
                        chunks.append(chunk)

    return chunks


def extract_brace_snippets(content: str, language_slug: str, max_lines: int = 35) -> list[str]:
    """Extract complete methods/functions and compact classes from brace-delimited languages."""
    lines = content.splitlines()
    chunks = []

    if language_slug in ("java", "csharp"):
        sig_pattern = re.compile(
            r"^\s*(class\s+\w+|namespace\s+\w+|(public|private|protected|static|final|async|override|virtual|\w+<[\w\s,]+>)\s+[\w<>,\[\]\s]+\s+\w+\s*\()"
        )
    elif language_slug == "javascript":
        sig_pattern = re.compile(
            r"^\s*(class\s+\w+|(export\s+)?(async\s+)?function\s+\w|^\s*(export\s+)?(const|let|var)\s+\w+\s*=\s*(async\s+)?\([^)]*\)\s*=>|^\s*(const|let|var)\s+\w+\s*=\s*(async\s+)?function)"
        )
    elif language_slug == "go":
        sig_pattern = re.compile(r"^func\s+(\([^)]+\)\s+)?\w+\s*\(|^type\s+\w+\s+(struct|interface)\s*\{")
    elif language_slug == "php":
        sig_pattern = re.compile(r"^\s*(class\s+\w+|(public|private|protected|static)?\s*function\s+\w+\s*\()")
    elif language_slug == "cpp":
        sig_pattern = re.compile(
            r"^\s*(class\s+\w+|struct\s+\w+|(void|int|bool|double|float|auto|std::\w+|template<[^>]+>\s+\w+)\s+\w+\s*\()"
        )
    else:
        sig_pattern = re.compile(r"^\s*(function|\w+)\s+\w+\s*\(")

    i = 0
    while i < len(lines):
        line = lines[i]
        if sig_pattern.search(line):
            depth = 0
            found_open = False
            start_idx = i
            end_idx = None
            for j in range(i, min(len(lines), i + max_lines + 5)):
                l = lines[j]
                for char in l:
                    if char == "{":
                        depth += 1
                        found_open = True
                    elif char == "}":
                        depth -= 1
                if found_open and depth == 0:
                    end_idx = j
                    break

            if end_idx is not None:
                block_lines = lines[start_idx : end_idx + 1]
                chunk = clean_snippet_code("\n".join(block_lines))
                ok, _ = is_valid_snippet(chunk, language_slug)
                if ok and len(chunk.splitlines()) <= max_lines:
                    chunks.append(chunk)
                i = end_idx + 1
                continue
        i += 1

    return chunks


def extract_css_snippets(content: str, max_lines: int = 35) -> list[str]:
    """Extract complete CSS rules."""
    cleaned = re.sub(r"/\*[\s\S]*?\*/", "", content)
    pattern = re.compile(r"([^{}]+)\s*\{([^}]+)\}")
    rules = []
    for match in pattern.finditer(cleaned):
        selector = match.group(1).strip()
        body = match.group(2).strip()
        if not selector or not body:
            continue
        props = [p.strip() for p in body.split(";") if p.strip()]
        if not props or len(props) > 18:
            continue
        rule = f"{selector} {{\n" + "\n".join(f"    {p};" for p in props) + "\n}"
        ok, _ = is_valid_snippet(rule, "css")
        if ok and len(rule.splitlines()) <= max_lines:
            rules.append(rule)
    return rules


def extract_sql_snippets(content: str, max_lines: int = 35) -> list[str]:
    """Extract clean SQL statements (rejecting Jinja macros)."""
    if "{%" in content or "{{" in content or "{#" in content:
        return []
    queries = []
    statements = content.split(";")
    for stmt in statements:
        s = clean_snippet_code(stmt)
        if not s:
            continue
        s = s + ";"
        ok, _ = is_valid_snippet(s, "sql")
        if ok and len(s.splitlines()) <= max_lines:
            queries.append(s)
    return queries


def extract_bash_snippets(content: str, max_lines: int = 35) -> list[str]:
    """Extract Bash functions and structured compound blocks (if-fi, loops)."""
    lines = content.splitlines()
    chunks = []
    start_pattern = re.compile(r"^\s*(function\s+\w+|\w+\s*\(\)\s*\{|if\s+\[|for\s+\w+|while\s+|case\s+)")

    i = 0
    while i < len(lines):
        line = lines[i]
        if start_pattern.search(line):
            # Check for brace block
            if "{" in line:
                depth = 0
                found_open = False
                end_idx = None
                for j in range(i, min(len(lines), i + max_lines + 5)):
                    for char in lines[j]:
                        if char == "{":
                            depth += 1
                            found_open = True
                        elif char == "}":
                            depth -= 1
                    if found_open and depth == 0:
                        end_idx = j
                        break
                if end_idx is not None:
                    block_lines = lines[i : end_idx + 1]
                    chunk = clean_snippet_code("\n".join(block_lines))
                    ok, _ = is_valid_snippet(chunk, "bash")
                    if ok and len(chunk.splitlines()) <= max_lines:
                        chunks.append(chunk)
                    i = end_idx + 1
                    continue
            else:
                # Check for if-fi, for-done, while-done
                end_token = None
                if re.match(r"^\s*if\s+", line):
                    end_token = "fi"
                elif re.match(r"^\s*(for|while)\s+", line):
                    end_token = "done"
                elif re.match(r"^\s*case\s+", line):
                    end_token = "esac"

                if end_token:
                    end_idx = None
                    for j in range(i + 3, min(len(lines), i + max_lines + 5)):
                        if lines[j].strip() == end_token or lines[j].strip().startswith(end_token + ";"):
                            end_idx = j
                            break
                    if end_idx is not None:
                        block_lines = lines[i : end_idx + 1]
                        chunk = clean_snippet_code("\n".join(block_lines))
                        ok, _ = is_valid_snippet(chunk, "bash")
                        if ok and len(chunk.splitlines()) <= max_lines:
                            chunks.append(chunk)
                        i = end_idx + 1
                        continue
        i += 1
    return chunks


def extract_html_snippets(content: str, max_lines: int = 35) -> list[str]:
    """Extract semantic HTML elements."""
    if "{%" in content or "{{" in content:
        return []
    tag_pattern = re.compile(
        r"<(form|nav|table|section|article|header|footer|div)\b[^>]*>[\s\S]*?</\1>",
        re.IGNORECASE
    )
    chunks = []
    for match in tag_pattern.finditer(content):
        chunk = clean_snippet_code(match.group(0))
        ok, _ = is_valid_snippet(chunk, "html")
        if ok and len(chunk.splitlines()) <= max_lines:
            chunks.append(chunk)
    return chunks


def extract_code_snippets(content: str, language_slug: str, max_lines: int = 35) -> list[str]:
    """Unified entry point to extract valid snippets for a given language."""
    if language_slug == "python":
        return extract_python_snippets(content, max_lines)
    elif language_slug in ("java", "javascript", "cpp", "csharp", "php", "go"):
        return extract_brace_snippets(content, language_slug, max_lines)
    elif language_slug == "css":
        return extract_css_snippets(content, max_lines)
    elif language_slug == "sql":
        return extract_sql_snippets(content, max_lines)
    elif language_slug == "html":
        return extract_html_snippets(content, max_lines)
    elif language_slug == "bash":
        return extract_bash_snippets(content, max_lines)
    return []


def extract_categorized_snippets(content: str, language_slug: str) -> dict[str, list[str]]:
    """
    Extract snippets categorized into easy (4-10 lines), medium (11-20 lines),
    and hard (21-35 lines).
    """
    chunks = extract_code_snippets(content, language_slug)
    categorized = {"easy": [], "medium": [], "hard": []}
    for chunk in chunks:
        n = len(chunk.splitlines())
        if 4 <= n <= 10:
            categorized["easy"].append(chunk)
        elif 11 <= n <= 20:
            categorized["medium"].append(chunk)
        elif 21 <= n <= 35:
            categorized["hard"].append(chunk)
    return categorized

